repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks: [end-of-file-fixer, trailing-whitespace, check-added-large-files]
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks: [black]
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks: [isort]
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.9
  hooks: [bandit]
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks: [detect-secrets]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.8
  hooks: [ruff]
