apiVersion: apps/v1
kind: Deployment
metadata:
  name: tractionbuild-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tractionbuild
  template:
    metadata:
      labels:
        app: tractionbuild
    spec:
      containers:
      - name: tractionbuild
        image: tractionbuild-test:latest # This now matches the name from your build log
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000