apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerotoship-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zerotoship
  template:
    metadata:
      labels:
        app: zerotoship
    spec:
      containers:
      - name: zerotoship
        image: zerotoship-test:latest # This now matches the name from your build log
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000