apiVersion: v1
kind: Pod
metadata:
  name: debug-auth
  namespace: zerotoship
spec:
  serviceAccountName: zerotoship
  containers:
  - name: debug
    image: busybox
    command: ['sleep', '3600']
  restartPolicy: Never